"""Initial_migration

Revision ID: f3ed05dd09d6
Revises: 
Create Date: 2026-02-12 15:49:19.408603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f3ed05dd09d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop saved_analyses
    try:
        with op.batch_alter_table('saved_analyses') as batch_op:
            batch_op.drop_index(op.f('ix_saved_analyses_id'))
    except Exception:
        pass # Index might not exist or table might not exist
        
    op.drop_table('saved_analyses')

    # brand_documents
    with op.batch_alter_table('brand_documents', schema=None) as batch_op:
        batch_op.alter_column('extracted_insights',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # brands
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('gemini_corpus_id')

    # knowledge_nodes
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_node_type'), ['node_type'], unique=False)
        batch_op.create_foreign_key('fk_knowledge_nodes_brands', 'brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key('fk_knowledge_nodes_docs', 'brand_documents', ['source_document_id'], ['id'])

    # knowledge_relations
    with op.batch_alter_table('knowledge_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_knowledge_relations_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_from_node_id'), ['from_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_to_node_id'), ['to_node_id'], unique=False)
        batch_op.create_foreign_key('fk_knowledge_relations_brands', 'brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key('fk_knowledge_relations_from_node', 'knowledge_nodes', ['from_node_id'], ['id'])
        batch_op.create_foreign_key('fk_knowledge_relations_to_node', 'knowledge_nodes', ['to_node_id'], ['id'])

    # personas
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('persona_subtype',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('disease_pack',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('specialty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('adherence_to_protocols',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('decision_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_personas_brand_id'), ['brand_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # personas
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personas_brand_id'))
        batch_op.alter_column('decision_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('adherence_to_protocols',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('specialty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('disease_pack',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('persona_subtype',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # knowledge_relations
    with op.batch_alter_table('knowledge_relations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_knowledge_relations_to_node', type_='foreignkey')
        batch_op.drop_constraint('fk_knowledge_relations_from_node', type_='foreignkey')
        batch_op.drop_constraint('fk_knowledge_relations_brands', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_to_node_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_from_node_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_brand_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # knowledge_nodes
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_knowledge_nodes_docs', type_='foreignkey')
        batch_op.drop_constraint('fk_knowledge_nodes_brands', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_node_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_brand_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # brands
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_corpus_id', sa.VARCHAR(), nullable=True))

    # brand_docum